version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./RAG
      dockerfile: Dockerfile
    ports:
      - "8000:8000"


volumes:
  db_user:
